template-file-path: packaged-stack.yaml

parameters:
  VpcCidr: 10.0.0.0/16
  PublicSubnetCidrs: 
    - 10.0.1.0/24
    - 10.0.2.0/24
  PrivateSubnetCidrs: 
    - 10.0.3.0/24
    - 10.0.4.0/24
  ProjectTag: week6-lab1
  ECSServiceName: GalleryXPAppService
  ECRRepoName: gallery-app-v2-ecr-repo
  AppName: GalleryApp-v2
  ECRImageTag: latest
  ContainerPort: 3000
  BranchName: main
  FullRepositoryId: drex7/aws-wk6-project-app

tags: {}
