AWSTemplateFormatVersion: "2010-09-09"
Description: Stack template for CodeDeploy resources

Parameters:
  AppName: { Type: String }
  ECSClusterName: { Type: String }
  ECSServiceName: { Type: String }
  BlueTargetGroupName: { Type: String }
  GreenTargetGroupName: { Type: String }
  ALBListenerArn: { Type: String }
  CodeDeployRoleArn: { Type: String }

Resources:
  CodeDeployApp:
    Type: AWS::CodeDeploy::Application
    Properties:
      ApplicationName: !Ref "${AppName}CodeDeployApp}"
      ComputePlatform: ECS

  DeploymentGroup:
    Type: AWS::CodeDeploy::DeploymentGroup
    Properties:
      ApplicationName: !Ref CodeDeployApp
      DeploymentGroupName: !Ref "${AppName}DeploymentGroup"
      DeploymentConfigName: CodeDeployDefault.ECSAllAtOnce
      ServiceRoleArn: !Ref CodeDeployRoleArn
      AutoRollbackConfiguration:
        Enabled: true
        Events: [DEPLOYMENT_FAILURE]
      BlueGreenDeploymentConfiguration:
        TerminateBlueInstancesOnDeploymentSuccess:
          Action: TERMINATE
          TerminationWaitTimeInMinutes: 2
        DeploymentReadyOption:
          ActionOnTimeout: CONTINUE_DEPLOYMENT
          WaitTimeInMinutes: 0
      DeploymentStyle:
        DeploymentType: BLUE_GREEN
        DeploymentOption: WITH_TRAFFIC_CONTROL
      LoadBalancerInfo:
        TargetGroupPairInfoList:
          - TargetGroups:
              - Name: !Ref GreenTargetGroupName
              - Name: !Ref BlueTargetGroupName
            ProdTrafficRoute:
              ListenerArns:
                - !Ref ALBListenerArn
      ECSServices:
        - ClusterName: !Ref ECSClusterName
          ServiceName: !Ref ECSServiceName

Outputs:
  CodeDeployAppName: { Value: !Ref CodeDeployApp }
  CodeDeployDeploymentGroupName: { Value: !Ref DeploymentGroup }
