AWSTemplateFormatVersion: "2010-09-09"
Description: Stack template for S# resources

Parameters:
  AppName: { Type: String }
  ALBDnsName: { Type: String }
  ECSTaskRoleArn: { Type: String }
  CodeDeployRoleArn: { Type: String }
  CodePipelineRoleArn: { Type: String }
  EventBridgeRoleArn: { Type: String }

Resources:
  # App S3 Bucket
  AppImagesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub webapp-images-v2-${AWS::AccountId}
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ['*']
            AllowedMethods: [GET, PUT, POST, DELETE]
            AllowedOrigins: 
              - !Join ['', ['http://', !Ref ALBDnsName]]
              - 'http://localhost:3000'
            MaxAge: 3000

  AppImagesBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref AppImagesBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: '*'
            Action:
              - s3:GetObject
            Resource: !Join ['', ['arn:aws:s3:::', !Ref AppImagesBucket, '/*']]
          - Effect: Allow
            Principal:
              AWS: !Ref ECSTaskRoleArn
            Action:
              - s3:ListBucket
            Resource: !Join ['', ['arn:aws:s3:::', !Ref AppImagesBucket]]
          - Effect: Allow
            Principal:
              AWS: !Ref ECSTaskRoleArn
            Action:
              - s3:GetObject
              - s3:PutObject
              - s3:DeleteObject
            Resource: !Join ['', ['arn:aws:s3:::', !Ref AppImagesBucket, '/*']]

  PipelineArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub codepipeline-artifacts-${AppName}-${AWS::AccountId}
      VersioningConfiguration:
        Status: Enabled

  PipelineArtifactBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref PipelineArtifactBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: 
              AWS: 
                - !Ref CodeDeployRoleArn
                - !Ref CodePipelineRoleArn
                - !Ref EventBridgeRoleArn
            Action:
              - s3:GetObject
              - s3:PutObject
              - s3:ListBucket
            Resource: 
              - !Sub ${PipelineArtifactBucket}
              - !Sub ${PipelineArtifactBucket}/*


Outputs:
  S3BucketName:
    Value: !Ref AppImagesBucket
  S3BucketArn:
    Value: !GetAtt AppImagesBucket.Arn
  PipelineArtifactBucketName:
    Value: !Ref PipelineArtifactBucket
  PipelineArtifactBucketArn:
    Value: !GetAtt PipelineArtifactBucket.Arn

